datasources:
  postgres:
    url: jdbc:postgresql://postgres:5432/kestra
    driverClassName: org.postgresql.Driver
    username: kestra
    password: k3str4
kestra:
  server:
    basicAuth:
      enabled: false
      username: admin
      password: kestra
  repository:
    type: postgres
  storage:
    type: minio
    minio:
      endpoint: http://minio
      port: 9000
      accessKey: admin
      secretKey: password
      region: us-east-1
      bucket: warehouse
  queue:
    type: postgres
  tasks:
    tmpDir:
      path: /tmp/kestra-wd/tmp
  url: http://localhost:8080/